/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FundFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "deployFund" | "deployedTokens"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FundDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployFund",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedTokens",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "deployFund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployedTokens",
    data: BytesLike
  ): Result;
}

export namespace FundDeployedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    name: string,
    owner: AddressLike
  ];
  export type OutputTuple = [tokenAddress: string, name: string, owner: string];
  export interface OutputObject {
    tokenAddress: string;
    name: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundFactory extends BaseContract {
  connect(runner?: ContractRunner | null): FundFactory;
  waitForDeployment(): Promise<this>;

  interface: FundFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployFund: TypedContractMethod<
    [name: string, symbol: string, initialOwner: AddressLike],
    [string],
    "nonpayable"
  >;

  deployedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployFund"
  ): TypedContractMethod<
    [name: string, symbol: string, initialOwner: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "FundDeployed"
  ): TypedContractEvent<
    FundDeployedEvent.InputTuple,
    FundDeployedEvent.OutputTuple,
    FundDeployedEvent.OutputObject
  >;

  filters: {
    "FundDeployed(address,string,address)": TypedContractEvent<
      FundDeployedEvent.InputTuple,
      FundDeployedEvent.OutputTuple,
      FundDeployedEvent.OutputObject
    >;
    FundDeployed: TypedContractEvent<
      FundDeployedEvent.InputTuple,
      FundDeployedEvent.OutputTuple,
      FundDeployedEvent.OutputObject
    >;
  };
}
