/** React Email templates and send helper. */
export { EmailFooter } from "./EmailFooter";
export { InvestorApproved } from "./InvestorApproved";
export { InvestorInvite } from "./InvestorInvite";
export { KycApproved } from "./KycApproved";
export { KycDeclinedGp } from "./KycDeclinedGp";
export { KycRejected } from "./KycRejected";
export { ApplicationReceived } from "./ApplicationReceived";
export { NewApplication } from "./NewApplication";
export { InvestorWhitelisted } from "./InvestorWhitelisted";
export { InvestorWhitelistedGp } from "./InvestorWhitelistedGp";
export { GpWelcome } from "./GpWelcome";
export { GpWelcomeSignup } from "./GpWelcomeSignup";
export { DailyDigest } from "./DailyDigest";
export { LpKycApproved } from "./LpKycApproved";
export { LpRejected } from "./LpRejected";
export { SubscriptionCanceled } from "./SubscriptionCanceled";
export { PaymentFailed } from "./PaymentFailed";
export { sendEmail } from "./send";
export type { SendEmailOptions, SendEmailResult } from "./send";
